import Link from "next/link";

const steps = [["01", "Spot the opportunity", "Kwikflow detects abandoned carts that deserve a personal follow-up."], ["02", "Create the draft", "A ready-to-review draft order is created in Shopify with the cart details in place."], ["03", "Close the sale", "Send the invoice or checkout link and bring the customer back when they are ready."]];

export default function Home() { return <main>
  <nav className="nav wrap"><Link className="brand" href="/"><span className="brand-mark">k</span>kwikflow</Link><div className="links"><a href="#how">How it works</a><a href="#why">Why Kwikflow</a><a className="pill" href="mailto:support@kwikflow.app">Get in touch</a></div></nav>
  <section className="hero wrap"><div><p className="eyebrow">● Built for Shopify stores</p><h1>Turn abandoned carts into <em>real orders.</em></h1><p className="lede">Kwikflow makes it easy to turn customer intent into a draft order your team can follow up on—without the manual busywork.</p><div className="actions"><a className="button orange" href="mailto:support@kwikflow.app">Start recovering carts →</a><a className="under" href="#how">See how it works ↓</a></div><p className="note">Simple setup · Lives inside Shopify · Human-ready follow-up</p></div><div className="card"><div className="bar">● ● ● <b>KWIKFLOW</b></div><div className="card-body"><div className="cart"><i>▢</i><div><strong>Cart abandoned</strong><small>2 items · $124.00</small></div><span>New</span></div><div className="down">↓</div><div className="cart done"><i>✓</i><div><strong>Draft order created</strong><small>Ready for your review</small></div><span>Ready</span></div><footer>Created in seconds <b>Open order →</b></footer></div></div></section>
  <section id="why" className="proof wrap">Not every abandoned cart is a lost sale. <b /> Make the next step effortless.</section>
  <section id="how" className="how"><div className="wrap"><p className="eyebrow">● A clearer recovery flow</p><div className="heading"><h2>From almost to<br /><em>order confirmed.</em></h2><p>Turn warm signals into a thoughtful, sales-ready next step. Kwikflow handles the setup so your team can focus on the conversation.</p></div><div className="steps">{steps.map(([number,title,text]) => <article key={number}><b>{number}</b><h3>{title}</h3><p>{text}</p><i>↘</i></article>)}</div></div></section>
  <section className="close wrap"><div><p className="eyebrow">● Keep the conversation moving</p><h2>Give every<br />cart a second chance.</h2></div><a className="button dark" href="mailto:support@kwikflow.app">Talk to us →</a></section>
  <footer className="site-footer wrap"><Link className="brand" href="/"><span className="brand-mark">k</span>kwikflow</Link><p>Better follow-up for Shopify stores.</p><Link href="/privacy-policy">Privacy policy</Link></footer>
</main>; }
